name: construction_supplies_erp_control_plane
version: 0.1.0
config-version: 2
profile: construction_supplies_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  construction_supplies_erp_control_plane:
    staging:
      +materialized: view
      +schema: staging
    canonical:
      +materialized: table
      +schema: canonical
    marts:
      +materialized: view
      +schema: marts

seeds:
  construction_supplies_erp_control_plane:
    +schema: reference
